syntax = "proto3";

package api.notes.v1;


import "api/notes/v1/messages.proto";

option go_package = "github.com/ArtamonovEvgenii/grpc-course-2025/pkg/api/notes/v1";

service NotesAPI {
  rpc CreateNote(CreateNoteRequest) returns(CreateNoteResponse) {}
  rpc GetNotesList(GetNotesListRequest) returns(GetNotesListResponse) {}
  rpc GetNote(GetNoteRequest) returns(GetNoteResponse) {}
  rpc UpdateNote(UpdateNoteRequest) returns(UpdateNoteResponse) {}
  rpc DeleteNote(DeleteNoteRequest) returns(DeleteNoteResponse) {}
}
