// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/notes/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_NONE           ErrorCode = 0
	ErrorCode_ERROR_CODE_NOTE_NOT_FOUND ErrorCode = 1
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_NONE",
		1: "ERROR_CODE_NOTE_NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_NONE":           0,
		"ERROR_CODE_NOTE_NOT_FOUND": 1,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notes_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_notes_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_notes_v1_errors_proto_rawDescGZIP(), []int{0}
}

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.notes.v1.ErrorCode" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetails) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *ErrorDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_api_notes_v1_errors_proto protoreflect.FileDescriptor

const file_api_notes_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x19api/notes/v1/errors.proto\x12\fapi.notes.v1\"]\n" +
	"\fErrorDetails\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.api.notes.v1.ErrorCodeR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*?\n" +
	"\tErrorCode\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x00\x12\x1d\n" +
	"\x19ERROR_CODE_NOTE_NOT_FOUND\x10\x01B?Z=github.com/ArtamonovEvgenii/grpc-course-2025/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_errors_proto_rawDescOnce sync.Once
	file_api_notes_v1_errors_proto_rawDescData []byte
)

func file_api_notes_v1_errors_proto_rawDescGZIP() []byte {
	file_api_notes_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)))
	})
	return file_api_notes_v1_errors_proto_rawDescData
}

var file_api_notes_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_notes_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_notes_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),       // 0: api.notes.v1.ErrorCode
	(*ErrorDetails)(nil), // 1: api.notes.v1.ErrorDetails
}
var file_api_notes_v1_errors_proto_depIdxs = []int32{
	0, // 0: api.notes.v1.ErrorDetails.code:type_name -> api.notes.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notes_v1_errors_proto_init() }
func file_api_notes_v1_errors_proto_init() {
	if File_api_notes_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_notes_v1_errors_proto_enumTypes,
		MessageInfos:      file_api_notes_v1_errors_proto_msgTypes,
	}.Build()
	File_api_notes_v1_errors_proto = out.File
	file_api_notes_v1_errors_proto_goTypes = nil
	file_api_notes_v1_errors_proto_depIdxs = nil
}
