// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/notes/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetNotesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListRequest) Reset() {
	*x = GetNotesListRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListRequest) ProtoMessage() {}

func (x *GetNotesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListRequest.ProtoReflect.Descriptor instead.
func (*GetNotesListRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{2}
}

type GetNotesListResponseNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt     *datetime.DateTime     `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListResponseNote) Reset() {
	*x = GetNotesListResponseNote{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListResponseNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListResponseNote) ProtoMessage() {}

func (x *GetNotesListResponseNote) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListResponseNote.ProtoReflect.Descriptor instead.
func (*GetNotesListResponseNote) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotesListResponseNote) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetNotesListResponseNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetNotesListResponseNote) GetUpdatedAt() *datetime.DateTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetNotesListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Notes         []*GetNotesListResponseNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListResponse) Reset() {
	*x = GetNotesListResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListResponse) ProtoMessage() {}

func (x *GetNotesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListResponse.ProtoReflect.Descriptor instead.
func (*GetNotesListResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotesListResponse) GetNotes() []*GetNotesListResponseNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CratedAt      *datetime.DateTime     `protobuf:"bytes,4,opt,name=crated_at,json=cratedAt,proto3" json:"crated_at,omitempty"`
	UpdatedAt     *datetime.DateTime     `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetNoteResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetNoteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetNoteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetNoteResponse) GetCratedAt() *datetime.DateTime {
	if x != nil {
		return x.CratedAt
	}
	return nil
}

func (x *GetNoteResponse) GetUpdatedAt() *datetime.DateTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{8}
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{10}
}

type SubscribeToEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToEventsRequest) Reset() {
	*x = SubscribeToEventsRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToEventsRequest) ProtoMessage() {}

func (x *SubscribeToEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{11}
}

type SubscribeToEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SubscribeToEventsResponse_Heartbeat
	//	*SubscribeToEventsResponse_CreatedNote
	Payload       isSubscribeToEventsResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToEventsResponse) Reset() {
	*x = SubscribeToEventsResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToEventsResponse) ProtoMessage() {}

func (x *SubscribeToEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeToEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeToEventsResponse) GetPayload() isSubscribeToEventsResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscribeToEventsResponse) GetHeartbeat() *HeartbeatEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeToEventsResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SubscribeToEventsResponse) GetCreatedNote() *CreateNoteEvent {
	if x != nil {
		if x, ok := x.Payload.(*SubscribeToEventsResponse_CreatedNote); ok {
			return x.CreatedNote
		}
	}
	return nil
}

type isSubscribeToEventsResponse_Payload interface {
	isSubscribeToEventsResponse_Payload()
}

type SubscribeToEventsResponse_Heartbeat struct {
	Heartbeat *HeartbeatEvent `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type SubscribeToEventsResponse_CreatedNote struct {
	CreatedNote *CreateNoteEvent `protobuf:"bytes,2,opt,name=created_note,json=createdNote,proto3,oneof"`
}

func (*SubscribeToEventsResponse_Heartbeat) isSubscribeToEventsResponse_Payload() {}

func (*SubscribeToEventsResponse_CreatedNote) isSubscribeToEventsResponse_Payload() {}

type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *datetime.DateTime     `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatEvent) GetTimestamp() *datetime.DateTime {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateNoteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteEvent) Reset() {
	*x = CreateNoteEvent{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteEvent) ProtoMessage() {}

func (x *CreateNoteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteEvent.ProtoReflect.Descriptor instead.
func (*CreateNoteEvent) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *CreateNoteEvent) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateNoteEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UploadMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsRequest) Reset() {
	*x = UploadMetricsRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsRequest) ProtoMessage() {}

func (x *UploadMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsRequest.ProtoReflect.Descriptor instead.
func (*UploadMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *UploadMetricsRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UploadMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int64                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsResponse) Reset() {
	*x = UploadMetricsResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsResponse) ProtoMessage() {}

func (x *UploadMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsResponse.ProtoReflect.Descriptor instead.
func (*UploadMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *UploadMetricsResponse) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type ChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageRequest) Reset() {
	*x = ChatMessageRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageRequest) ProtoMessage() {}

func (x *ChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageRequest.ProtoReflect.Descriptor instead.
func (*ChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *ChatMessageRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatMessageResponse_Success
	//	*ChatMessageResponse_Error
	Payload       isChatMessageResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageResponse) Reset() {
	*x = ChatMessageResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageResponse) ProtoMessage() {}

func (x *ChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ChatMessageResponse) GetPayload() isChatMessageResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatMessageResponse) GetSuccess() *ChatMessageSuccessResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessageResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ChatMessageResponse) GetError() *ChatMessageErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*ChatMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatMessageResponse_Payload interface {
	isChatMessageResponse_Payload()
}

type ChatMessageResponse_Success struct {
	Success *ChatMessageSuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ChatMessageResponse_Error struct {
	Error *ChatMessageErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ChatMessageResponse_Success) isChatMessageResponse_Payload() {}

func (*ChatMessageResponse_Error) isChatMessageResponse_Payload() {}

type ChatMessageSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageSuccessResponse) Reset() {
	*x = ChatMessageSuccessResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageSuccessResponse) ProtoMessage() {}

func (x *ChatMessageSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageSuccessResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageSuccessResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ChatMessageSuccessResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessageSuccessResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ChatMessageErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageErrorResponse) Reset() {
	*x = ChatMessageErrorResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageErrorResponse) ProtoMessage() {}

func (x *ChatMessageErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageErrorResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ChatMessageErrorResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ChatMessageErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_notes_v1_messages_proto protoreflect.FileDescriptor

const file_api_notes_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/notes/v1/messages.proto\x12\fapi.notes.v1\x1a\x1agoogle/type/datetime.proto\x1a\x1bbuf/validate/validate.proto\"\x95\x01\n" +
	"\x11CreateNoteRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x05\x18\xff\x01R\x05title\x12\x1b\n" +
	"\x04text\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\n" +
	"R\x04text:A\xbaH>\x1a<\x12!title should not be equal to text\x1a\x17this.title != this.text\"(\n" +
	"\x12CreateNoteResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x15\n" +
	"\x13GetNotesListRequest\"z\n" +
	"\x18GetNotesListResponseNote\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x124\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x15.google.type.DateTimeR\tupdatedAt\"T\n" +
	"\x14GetNotesListResponse\x12<\n" +
	"\x05notes\x18\x01 \x03(\v2&.api.notes.v1.GetNotesListResponseNoteR\x05notes\".\n" +
	"\x0eGetNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"\xb9\x01\n" +
	"\x0fGetNoteResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x122\n" +
	"\tcrated_at\x18\x04 \x01(\v2\x15.google.type.DateTimeR\bcratedAt\x124\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x15.google.type.DateTimeR\tupdatedAt\"p\n" +
	"\x11UpdateNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12 \n" +
	"\x05title\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x05\x18\xff\x01R\x05title\x12\x1b\n" +
	"\x04text\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\n" +
	"R\x04text\"\x14\n" +
	"\x12UpdateNoteResponse\"1\n" +
	"\x11DeleteNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"\x14\n" +
	"\x12DeleteNoteResponse\"\x1a\n" +
	"\x18SubscribeToEventsRequest\"\xa8\x01\n" +
	"\x19SubscribeToEventsResponse\x12<\n" +
	"\theartbeat\x18\x01 \x01(\v2\x1c.api.notes.v1.HeartbeatEventH\x00R\theartbeat\x12B\n" +
	"\fcreated_note\x18\x02 \x01(\v2\x1d.api.notes.v1.CreateNoteEventH\x00R\vcreatedNoteB\t\n" +
	"\apayload\"E\n" +
	"\x0eHeartbeatEvent\x123\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x15.google.type.DateTimeR\ttimestamp\";\n" +
	"\x0fCreateNoteEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\",\n" +
	"\x14UploadMetricsRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\")\n" +
	"\x15UploadMetricsResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x03R\x03sum\"O\n" +
	"\x12ChatMessageRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xa6\x01\n" +
	"\x13ChatMessageResponse\x12D\n" +
	"\asuccess\x18\x01 \x01(\v2(.api.notes.v1.ChatMessageSuccessResponseH\x00R\asuccess\x12>\n" +
	"\x05error\x18\x02 \x01(\v2&.api.notes.v1.ChatMessageErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"W\n" +
	"\x1aChatMessageSuccessResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"W\n" +
	"\x18ChatMessageErrorResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB?Z=github.com/ArtamonovEvgenii/grpc-course-2025/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_messages_proto_rawDescOnce sync.Once
	file_api_notes_v1_messages_proto_rawDescData []byte
)

func file_api_notes_v1_messages_proto_rawDescGZIP() []byte {
	file_api_notes_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)))
	})
	return file_api_notes_v1_messages_proto_rawDescData
}

var file_api_notes_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_notes_v1_messages_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),          // 0: api.notes.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil),         // 1: api.notes.v1.CreateNoteResponse
	(*GetNotesListRequest)(nil),        // 2: api.notes.v1.GetNotesListRequest
	(*GetNotesListResponseNote)(nil),   // 3: api.notes.v1.GetNotesListResponseNote
	(*GetNotesListResponse)(nil),       // 4: api.notes.v1.GetNotesListResponse
	(*GetNoteRequest)(nil),             // 5: api.notes.v1.GetNoteRequest
	(*GetNoteResponse)(nil),            // 6: api.notes.v1.GetNoteResponse
	(*UpdateNoteRequest)(nil),          // 7: api.notes.v1.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),         // 8: api.notes.v1.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),          // 9: api.notes.v1.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),         // 10: api.notes.v1.DeleteNoteResponse
	(*SubscribeToEventsRequest)(nil),   // 11: api.notes.v1.SubscribeToEventsRequest
	(*SubscribeToEventsResponse)(nil),  // 12: api.notes.v1.SubscribeToEventsResponse
	(*HeartbeatEvent)(nil),             // 13: api.notes.v1.HeartbeatEvent
	(*CreateNoteEvent)(nil),            // 14: api.notes.v1.CreateNoteEvent
	(*UploadMetricsRequest)(nil),       // 15: api.notes.v1.UploadMetricsRequest
	(*UploadMetricsResponse)(nil),      // 16: api.notes.v1.UploadMetricsResponse
	(*ChatMessageRequest)(nil),         // 17: api.notes.v1.ChatMessageRequest
	(*ChatMessageResponse)(nil),        // 18: api.notes.v1.ChatMessageResponse
	(*ChatMessageSuccessResponse)(nil), // 19: api.notes.v1.ChatMessageSuccessResponse
	(*ChatMessageErrorResponse)(nil),   // 20: api.notes.v1.ChatMessageErrorResponse
	(*datetime.DateTime)(nil),          // 21: google.type.DateTime
}
var file_api_notes_v1_messages_proto_depIdxs = []int32{
	21, // 0: api.notes.v1.GetNotesListResponseNote.updated_at:type_name -> google.type.DateTime
	3,  // 1: api.notes.v1.GetNotesListResponse.notes:type_name -> api.notes.v1.GetNotesListResponseNote
	21, // 2: api.notes.v1.GetNoteResponse.crated_at:type_name -> google.type.DateTime
	21, // 3: api.notes.v1.GetNoteResponse.updated_at:type_name -> google.type.DateTime
	13, // 4: api.notes.v1.SubscribeToEventsResponse.heartbeat:type_name -> api.notes.v1.HeartbeatEvent
	14, // 5: api.notes.v1.SubscribeToEventsResponse.created_note:type_name -> api.notes.v1.CreateNoteEvent
	21, // 6: api.notes.v1.HeartbeatEvent.timestamp:type_name -> google.type.DateTime
	19, // 7: api.notes.v1.ChatMessageResponse.success:type_name -> api.notes.v1.ChatMessageSuccessResponse
	20, // 8: api.notes.v1.ChatMessageResponse.error:type_name -> api.notes.v1.ChatMessageErrorResponse
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_notes_v1_messages_proto_init() }
func file_api_notes_v1_messages_proto_init() {
	if File_api_notes_v1_messages_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_msgTypes[12].OneofWrappers = []any{
		(*SubscribeToEventsResponse_Heartbeat)(nil),
		(*SubscribeToEventsResponse_CreatedNote)(nil),
	}
	file_api_notes_v1_messages_proto_msgTypes[18].OneofWrappers = []any{
		(*ChatMessageResponse_Success)(nil),
		(*ChatMessageResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_notes_v1_messages_proto_msgTypes,
	}.Build()
	File_api_notes_v1_messages_proto = out.File
	file_api_notes_v1_messages_proto_goTypes = nil
	file_api_notes_v1_messages_proto_depIdxs = nil
}
