// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/notes/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetNotesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListRequest) Reset() {
	*x = GetNotesListRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListRequest) ProtoMessage() {}

func (x *GetNotesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListRequest.ProtoReflect.Descriptor instead.
func (*GetNotesListRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{2}
}

type GetNotesListResponseNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt     *datetime.DateTime     `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListResponseNote) Reset() {
	*x = GetNotesListResponseNote{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListResponseNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListResponseNote) ProtoMessage() {}

func (x *GetNotesListResponseNote) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListResponseNote.ProtoReflect.Descriptor instead.
func (*GetNotesListResponseNote) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotesListResponseNote) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetNotesListResponseNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetNotesListResponseNote) GetUpdatedAt() *datetime.DateTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetNotesListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Notes         []*GetNotesListResponseNote `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotesListResponse) Reset() {
	*x = GetNotesListResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotesListResponse) ProtoMessage() {}

func (x *GetNotesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotesListResponse.ProtoReflect.Descriptor instead.
func (*GetNotesListResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotesListResponse) GetNotes() []*GetNotesListResponseNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CratedAt      *datetime.DateTime     `protobuf:"bytes,4,opt,name=crated_at,json=cratedAt,proto3" json:"crated_at,omitempty"`
	UpdatedAt     *datetime.DateTime     `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteResponse) Reset() {
	*x = GetNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteResponse) ProtoMessage() {}

func (x *GetNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteResponse.ProtoReflect.Descriptor instead.
func (*GetNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetNoteResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetNoteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetNoteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetNoteResponse) GetCratedAt() *datetime.DateTime {
	if x != nil {
		return x.CratedAt
	}
	return nil
}

func (x *GetNoteResponse) GetUpdatedAt() *datetime.DateTime {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteResponse) Reset() {
	*x = UpdateNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteResponse) ProtoMessage() {}

func (x *UpdateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{8}
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNoteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteResponse) Reset() {
	*x = DeleteNoteResponse{}
	mi := &file_api_notes_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteResponse) ProtoMessage() {}

func (x *DeleteNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteResponse.ProtoReflect.Descriptor instead.
func (*DeleteNoteResponse) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_messages_proto_rawDescGZIP(), []int{10}
}

var File_api_notes_v1_messages_proto protoreflect.FileDescriptor

const file_api_notes_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/notes/v1/messages.proto\x12\fapi.notes.v1\x1a\x1agoogle/type/datetime.proto\x1a\x1bbuf/validate/validate.proto\"R\n" +
	"\x11CreateNoteRequest\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x05\x18\xff\x01R\x05title\x12\x1b\n" +
	"\x04text\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\n" +
	"R\x04text\"(\n" +
	"\x12CreateNoteResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x15\n" +
	"\x13GetNotesListRequest\"z\n" +
	"\x18GetNotesListResponseNote\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x124\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x15.google.type.DateTimeR\tupdatedAt\"T\n" +
	"\x14GetNotesListResponse\x12<\n" +
	"\x05notes\x18\x01 \x03(\v2&.api.notes.v1.GetNotesListResponseNoteR\x05notes\".\n" +
	"\x0eGetNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"\xb9\x01\n" +
	"\x0fGetNoteResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x122\n" +
	"\tcrated_at\x18\x04 \x01(\v2\x15.google.type.DateTimeR\bcratedAt\x124\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x15.google.type.DateTimeR\tupdatedAt\"p\n" +
	"\x11UpdateNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x12 \n" +
	"\x05title\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x05\x18\xff\x01R\x05title\x12\x1b\n" +
	"\x04text\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\n" +
	"R\x04text\"\x14\n" +
	"\x12UpdateNoteResponse\"1\n" +
	"\x11DeleteNoteRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"\x14\n" +
	"\x12DeleteNoteResponseB?Z=github.com/ArtamonovEvgenii/grpc-course-2025/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_messages_proto_rawDescOnce sync.Once
	file_api_notes_v1_messages_proto_rawDescData []byte
)

func file_api_notes_v1_messages_proto_rawDescGZIP() []byte {
	file_api_notes_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)))
	})
	return file_api_notes_v1_messages_proto_rawDescData
}

var file_api_notes_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_notes_v1_messages_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),        // 0: api.notes.v1.CreateNoteRequest
	(*CreateNoteResponse)(nil),       // 1: api.notes.v1.CreateNoteResponse
	(*GetNotesListRequest)(nil),      // 2: api.notes.v1.GetNotesListRequest
	(*GetNotesListResponseNote)(nil), // 3: api.notes.v1.GetNotesListResponseNote
	(*GetNotesListResponse)(nil),     // 4: api.notes.v1.GetNotesListResponse
	(*GetNoteRequest)(nil),           // 5: api.notes.v1.GetNoteRequest
	(*GetNoteResponse)(nil),          // 6: api.notes.v1.GetNoteResponse
	(*UpdateNoteRequest)(nil),        // 7: api.notes.v1.UpdateNoteRequest
	(*UpdateNoteResponse)(nil),       // 8: api.notes.v1.UpdateNoteResponse
	(*DeleteNoteRequest)(nil),        // 9: api.notes.v1.DeleteNoteRequest
	(*DeleteNoteResponse)(nil),       // 10: api.notes.v1.DeleteNoteResponse
	(*datetime.DateTime)(nil),        // 11: google.type.DateTime
}
var file_api_notes_v1_messages_proto_depIdxs = []int32{
	11, // 0: api.notes.v1.GetNotesListResponseNote.updated_at:type_name -> google.type.DateTime
	3,  // 1: api.notes.v1.GetNotesListResponse.notes:type_name -> api.notes.v1.GetNotesListResponseNote
	11, // 2: api.notes.v1.GetNoteResponse.crated_at:type_name -> google.type.DateTime
	11, // 3: api.notes.v1.GetNoteResponse.updated_at:type_name -> google.type.DateTime
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_notes_v1_messages_proto_init() }
func file_api_notes_v1_messages_proto_init() {
	if File_api_notes_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_messages_proto_rawDesc), len(file_api_notes_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_notes_v1_messages_proto_msgTypes,
	}.Build()
	File_api_notes_v1_messages_proto = out.File
	file_api_notes_v1_messages_proto_goTypes = nil
	file_api_notes_v1_messages_proto_depIdxs = nil
}
