// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotesAPI_CreateNote_FullMethodName        = "/api.notes.v1.NotesAPI/CreateNote"
	NotesAPI_GetNotesList_FullMethodName      = "/api.notes.v1.NotesAPI/GetNotesList"
	NotesAPI_GetNote_FullMethodName           = "/api.notes.v1.NotesAPI/GetNote"
	NotesAPI_UpdateNote_FullMethodName        = "/api.notes.v1.NotesAPI/UpdateNote"
	NotesAPI_DeleteNote_FullMethodName        = "/api.notes.v1.NotesAPI/DeleteNote"
	NotesAPI_SubscribeToEvents_FullMethodName = "/api.notes.v1.NotesAPI/SubscribeToEvents"
	NotesAPI_UploadMetrics_FullMethodName     = "/api.notes.v1.NotesAPI/UploadMetrics"
	NotesAPI_Chat_FullMethodName              = "/api.notes.v1.NotesAPI/Chat"
)

// NotesAPIClient is the client API for NotesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotesAPIClient interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error)
	GetNotesList(ctx context.Context, in *GetNotesListRequest, opts ...grpc.CallOption) (*GetNotesListResponse, error)
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
	SubscribeToEvents(ctx context.Context, in *SubscribeToEventsRequest, opts ...grpc.CallOption) (NotesAPI_SubscribeToEventsClient, error)
	UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (NotesAPI_UploadMetricsClient, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (NotesAPI_ChatClient, error)
}

type notesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNotesAPIClient(cc grpc.ClientConnInterface) NotesAPIClient {
	return &notesAPIClient{cc}
}

func (c *notesAPIClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*CreateNoteResponse, error) {
	out := new(CreateNoteResponse)
	err := c.cc.Invoke(ctx, NotesAPI_CreateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesAPIClient) GetNotesList(ctx context.Context, in *GetNotesListRequest, opts ...grpc.CallOption) (*GetNotesListResponse, error) {
	out := new(GetNotesListResponse)
	err := c.cc.Invoke(ctx, NotesAPI_GetNotesList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesAPIClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, NotesAPI_GetNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesAPIClient) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*UpdateNoteResponse, error) {
	out := new(UpdateNoteResponse)
	err := c.cc.Invoke(ctx, NotesAPI_UpdateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesAPIClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, NotesAPI_DeleteNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notesAPIClient) SubscribeToEvents(ctx context.Context, in *SubscribeToEventsRequest, opts ...grpc.CallOption) (NotesAPI_SubscribeToEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotesAPI_ServiceDesc.Streams[0], NotesAPI_SubscribeToEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notesAPISubscribeToEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotesAPI_SubscribeToEventsClient interface {
	Recv() (*SubscribeToEventsResponse, error)
	grpc.ClientStream
}

type notesAPISubscribeToEventsClient struct {
	grpc.ClientStream
}

func (x *notesAPISubscribeToEventsClient) Recv() (*SubscribeToEventsResponse, error) {
	m := new(SubscribeToEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *notesAPIClient) UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (NotesAPI_UploadMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotesAPI_ServiceDesc.Streams[1], NotesAPI_UploadMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notesAPIUploadMetricsClient{stream}
	return x, nil
}

type NotesAPI_UploadMetricsClient interface {
	Send(*UploadMetricsRequest) error
	CloseAndRecv() (*UploadMetricsResponse, error)
	grpc.ClientStream
}

type notesAPIUploadMetricsClient struct {
	grpc.ClientStream
}

func (x *notesAPIUploadMetricsClient) Send(m *UploadMetricsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notesAPIUploadMetricsClient) CloseAndRecv() (*UploadMetricsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *notesAPIClient) Chat(ctx context.Context, opts ...grpc.CallOption) (NotesAPI_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotesAPI_ServiceDesc.Streams[2], NotesAPI_Chat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notesAPIChatClient{stream}
	return x, nil
}

type NotesAPI_ChatClient interface {
	Send(*ChatMessageRequest) error
	Recv() (*ChatMessageResponse, error)
	grpc.ClientStream
}

type notesAPIChatClient struct {
	grpc.ClientStream
}

func (x *notesAPIChatClient) Send(m *ChatMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notesAPIChatClient) Recv() (*ChatMessageResponse, error) {
	m := new(ChatMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotesAPIServer is the server API for NotesAPI service.
// All implementations should embed UnimplementedNotesAPIServer
// for forward compatibility
type NotesAPIServer interface {
	CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error)
	GetNotesList(context.Context, *GetNotesListRequest) (*GetNotesListResponse, error)
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error)
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	SubscribeToEvents(*SubscribeToEventsRequest, NotesAPI_SubscribeToEventsServer) error
	UploadMetrics(NotesAPI_UploadMetricsServer) error
	Chat(NotesAPI_ChatServer) error
}

// UnimplementedNotesAPIServer should be embedded to have forward compatible implementations.
type UnimplementedNotesAPIServer struct {
}

func (UnimplementedNotesAPIServer) CreateNote(context.Context, *CreateNoteRequest) (*CreateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNotesAPIServer) GetNotesList(context.Context, *GetNotesListRequest) (*GetNotesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotesList not implemented")
}
func (UnimplementedNotesAPIServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNotesAPIServer) UpdateNote(context.Context, *UpdateNoteRequest) (*UpdateNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedNotesAPIServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedNotesAPIServer) SubscribeToEvents(*SubscribeToEventsRequest, NotesAPI_SubscribeToEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedNotesAPIServer) UploadMetrics(NotesAPI_UploadMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMetrics not implemented")
}
func (UnimplementedNotesAPIServer) Chat(NotesAPI_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

// UnsafeNotesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotesAPIServer will
// result in compilation errors.
type UnsafeNotesAPIServer interface {
	mustEmbedUnimplementedNotesAPIServer()
}

func RegisterNotesAPIServer(s grpc.ServiceRegistrar, srv NotesAPIServer) {
	s.RegisterService(&NotesAPI_ServiceDesc, srv)
}

func _NotesAPI_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesAPIServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotesAPI_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesAPIServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotesAPI_GetNotesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesAPIServer).GetNotesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotesAPI_GetNotesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesAPIServer).GetNotesList(ctx, req.(*GetNotesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotesAPI_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesAPIServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotesAPI_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesAPIServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotesAPI_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesAPIServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotesAPI_UpdateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesAPIServer).UpdateNote(ctx, req.(*UpdateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotesAPI_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotesAPIServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotesAPI_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotesAPIServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotesAPI_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotesAPIServer).SubscribeToEvents(m, &notesAPISubscribeToEventsServer{stream})
}

type NotesAPI_SubscribeToEventsServer interface {
	Send(*SubscribeToEventsResponse) error
	grpc.ServerStream
}

type notesAPISubscribeToEventsServer struct {
	grpc.ServerStream
}

func (x *notesAPISubscribeToEventsServer) Send(m *SubscribeToEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NotesAPI_UploadMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotesAPIServer).UploadMetrics(&notesAPIUploadMetricsServer{stream})
}

type NotesAPI_UploadMetricsServer interface {
	SendAndClose(*UploadMetricsResponse) error
	Recv() (*UploadMetricsRequest, error)
	grpc.ServerStream
}

type notesAPIUploadMetricsServer struct {
	grpc.ServerStream
}

func (x *notesAPIUploadMetricsServer) SendAndClose(m *UploadMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notesAPIUploadMetricsServer) Recv() (*UploadMetricsRequest, error) {
	m := new(UploadMetricsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NotesAPI_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotesAPIServer).Chat(&notesAPIChatServer{stream})
}

type NotesAPI_ChatServer interface {
	Send(*ChatMessageResponse) error
	Recv() (*ChatMessageRequest, error)
	grpc.ServerStream
}

type notesAPIChatServer struct {
	grpc.ServerStream
}

func (x *notesAPIChatServer) Send(m *ChatMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notesAPIChatServer) Recv() (*ChatMessageRequest, error) {
	m := new(ChatMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotesAPI_ServiceDesc is the grpc.ServiceDesc for NotesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NotesAPI",
	HandlerType: (*NotesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _NotesAPI_CreateNote_Handler,
		},
		{
			MethodName: "GetNotesList",
			Handler:    _NotesAPI_GetNotesList_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _NotesAPI_GetNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _NotesAPI_UpdateNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _NotesAPI_DeleteNote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _NotesAPI_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadMetrics",
			Handler:       _NotesAPI_UploadMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _NotesAPI_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/notes/v1/notes.proto",
}
