// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/notes/v1/notes.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_notes_v1_notes_proto protoreflect.FileDescriptor

const file_api_notes_v1_notes_proto_rawDesc = "" +
	"\n" +
	"\x18api/notes/v1/notes.proto\x12\fapi.notes.v1\x1a\x1bapi/notes/v1/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xa6\a\n" +
	"\bNotesAPI\x12p\n" +
	"\n" +
	"CreateNote\x12\x1f.api.notes.v1.CreateNoteRequest\x1a .api.notes.v1.CreateNoteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/notes/create\x12l\n" +
	"\fGetNotesList\x12!.api.notes.v1.GetNotesListRequest\x1a\".api.notes.v1.GetNotesListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/notes\x12d\n" +
	"\aGetNote\x12\x1c.api.notes.v1.GetNoteRequest\x1a\x1d.api.notes.v1.GetNoteResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/notes/{uuid}\x12p\n" +
	"\n" +
	"UpdateNote\x12\x1f.api.notes.v1.UpdateNoteRequest\x1a .api.notes.v1.UpdateNoteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/notes/update\x12p\n" +
	"\n" +
	"DeleteNote\x12\x1f.api.notes.v1.DeleteNoteRequest\x1a .api.notes.v1.DeleteNoteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/notes/delete\x12\x85\x01\n" +
	"\x11SubscribeToEvents\x12&.api.notes.v1.SubscribeToEventsRequest\x1a'.api.notes.v1.SubscribeToEventsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/stream/events0\x01\x12z\n" +
	"\rUploadMetrics\x12\".api.notes.v1.UploadMetricsRequest\x1a#.api.notes.v1.UploadMetricsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/stream/metrics(\x01\x12l\n" +
	"\x04Chat\x12 .api.notes.v1.ChatMessageRequest\x1a!.api.notes.v1.ChatMessageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/stream/chat(\x010\x01B?Z=github.com/ArtamonovEvgenii/grpc-course-2025/pkg/api/notes/v1b\x06proto3"

var file_api_notes_v1_notes_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),         // 0: api.notes.v1.CreateNoteRequest
	(*GetNotesListRequest)(nil),       // 1: api.notes.v1.GetNotesListRequest
	(*GetNoteRequest)(nil),            // 2: api.notes.v1.GetNoteRequest
	(*UpdateNoteRequest)(nil),         // 3: api.notes.v1.UpdateNoteRequest
	(*DeleteNoteRequest)(nil),         // 4: api.notes.v1.DeleteNoteRequest
	(*SubscribeToEventsRequest)(nil),  // 5: api.notes.v1.SubscribeToEventsRequest
	(*UploadMetricsRequest)(nil),      // 6: api.notes.v1.UploadMetricsRequest
	(*ChatMessageRequest)(nil),        // 7: api.notes.v1.ChatMessageRequest
	(*CreateNoteResponse)(nil),        // 8: api.notes.v1.CreateNoteResponse
	(*GetNotesListResponse)(nil),      // 9: api.notes.v1.GetNotesListResponse
	(*GetNoteResponse)(nil),           // 10: api.notes.v1.GetNoteResponse
	(*UpdateNoteResponse)(nil),        // 11: api.notes.v1.UpdateNoteResponse
	(*DeleteNoteResponse)(nil),        // 12: api.notes.v1.DeleteNoteResponse
	(*SubscribeToEventsResponse)(nil), // 13: api.notes.v1.SubscribeToEventsResponse
	(*UploadMetricsResponse)(nil),     // 14: api.notes.v1.UploadMetricsResponse
	(*ChatMessageResponse)(nil),       // 15: api.notes.v1.ChatMessageResponse
}
var file_api_notes_v1_notes_proto_depIdxs = []int32{
	0,  // 0: api.notes.v1.NotesAPI.CreateNote:input_type -> api.notes.v1.CreateNoteRequest
	1,  // 1: api.notes.v1.NotesAPI.GetNotesList:input_type -> api.notes.v1.GetNotesListRequest
	2,  // 2: api.notes.v1.NotesAPI.GetNote:input_type -> api.notes.v1.GetNoteRequest
	3,  // 3: api.notes.v1.NotesAPI.UpdateNote:input_type -> api.notes.v1.UpdateNoteRequest
	4,  // 4: api.notes.v1.NotesAPI.DeleteNote:input_type -> api.notes.v1.DeleteNoteRequest
	5,  // 5: api.notes.v1.NotesAPI.SubscribeToEvents:input_type -> api.notes.v1.SubscribeToEventsRequest
	6,  // 6: api.notes.v1.NotesAPI.UploadMetrics:input_type -> api.notes.v1.UploadMetricsRequest
	7,  // 7: api.notes.v1.NotesAPI.Chat:input_type -> api.notes.v1.ChatMessageRequest
	8,  // 8: api.notes.v1.NotesAPI.CreateNote:output_type -> api.notes.v1.CreateNoteResponse
	9,  // 9: api.notes.v1.NotesAPI.GetNotesList:output_type -> api.notes.v1.GetNotesListResponse
	10, // 10: api.notes.v1.NotesAPI.GetNote:output_type -> api.notes.v1.GetNoteResponse
	11, // 11: api.notes.v1.NotesAPI.UpdateNote:output_type -> api.notes.v1.UpdateNoteResponse
	12, // 12: api.notes.v1.NotesAPI.DeleteNote:output_type -> api.notes.v1.DeleteNoteResponse
	13, // 13: api.notes.v1.NotesAPI.SubscribeToEvents:output_type -> api.notes.v1.SubscribeToEventsResponse
	14, // 14: api.notes.v1.NotesAPI.UploadMetrics:output_type -> api.notes.v1.UploadMetricsResponse
	15, // 15: api.notes.v1.NotesAPI.Chat:output_type -> api.notes.v1.ChatMessageResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_v1_notes_proto_init() }
func file_api_notes_v1_notes_proto_init() {
	if File_api_notes_v1_notes_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_notes_proto_rawDesc), len(file_api_notes_v1_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_notes_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_notes_proto_depIdxs,
	}.Build()
	File_api_notes_v1_notes_proto = out.File
	file_api_notes_v1_notes_proto_goTypes = nil
	file_api_notes_v1_notes_proto_depIdxs = nil
}
